export type PromptEntry = {
  id: number;
  text: string;
  displayType: "fragment" | "lighthearted-fragment" | "prompt";
  tvmazeTypes: string[];
  genres: string[];
  progressTags: string[];
  themes: string[];
};

export const PROMPT_DATA: PromptEntry[] = [
  // ── Fragments ──────────────────────────────────────────────────────────────
  {
    id: 1,
    text: "something that stayed with you...",
    displayType: "fragment",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["contemplative", "visceral"],
  },
  {
    id: 2,
    text: "a moment you didn't expect...",
    displayType: "fragment",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["visceral", "craft"],
  },
  {
    id: 3,
    text: "what you're still thinking about...",
    displayType: "fragment",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["contemplative"],
  },
  {
    id: 4,
    text: "the scene you keep returning to...",
    displayType: "fragment",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["visceral", "contemplative"],
  },
  {
    id: 5,
    text: "what surprised you this time...",
    displayType: "fragment",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["visceral"],
  },
  {
    id: 6,
    text: "a detail you almost missed...",
    displayType: "fragment",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["craft", "contemplative"],
  },
  {
    id: 7,
    text: "what it made you feel, exactly...",
    displayType: "fragment",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["visceral", "personal"],
  },
  {
    id: 8,
    text: "where you are with it...",
    displayType: "fragment",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["contemplative", "personal"],
  },
  {
    id: 9,
    text: "a question it left you with...",
    displayType: "fragment",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["contemplative"],
  },
  {
    id: 10,
    text: "something you're still processing...",
    displayType: "fragment",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["contemplative", "visceral"],
  },
  {
    id: 11,
    text: "what you didn't see coming...",
    displayType: "fragment",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["visceral", "prediction"],
  },
  {
    id: 12,
    text: "the moment it shifted for you...",
    displayType: "fragment",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["visceral", "contemplative"],
  },
  {
    id: 13,
    text: "what this one is doing to you...",
    displayType: "fragment",
    tvmazeTypes: ["Scripted", "Documentary"],
    genres: ["Drama", "Thriller", "Crime", "Horror"],
    progressTags: ["any-progress"],
    themes: ["visceral", "personal"],
  },
  {
    id: 14,
    text: "where your mind keeps going...",
    displayType: "fragment",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["contemplative"],
  },
  {
    id: 15,
    text: "the part that felt uncomfortably true...",
    displayType: "fragment",
    tvmazeTypes: ["Scripted", "Documentary"],
    genres: ["Drama", "Crime", "Thriller"],
    progressTags: ["any-progress"],
    themes: ["personal", "visceral"],
  },
  {
    id: 16,
    text: "what you'd say if someone asked you to explain it...",
    displayType: "fragment",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["contemplative", "connection"],
  },
  {
    id: 17,
    text: "what this episode cost you emotionally...",
    displayType: "fragment",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller", "Horror"],
    progressTags: ["any-progress"],
    themes: ["visceral", "personal"],
  },
  {
    id: 18,
    text: "the character you can't stop thinking about...",
    displayType: "fragment",
    tvmazeTypes: ["Scripted", "Animation"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["character"],
  },
  {
    id: 19,
    text: "what you're carrying out of this one...",
    displayType: "fragment",
    tvmazeTypes: ["Scripted", "Documentary"],
    genres: ["Drama", "Thriller", "Crime"],
    progressTags: ["any-progress"],
    themes: ["contemplative", "personal"],
  },
  // ── Lighthearted Fragments ─────────────────────────────────────────────────
  {
    id: 20,
    text: "what made you laugh out loud...",
    displayType: "lighthearted-fragment",
    tvmazeTypes: ["Reality", "Game Show"],
    genres: ["Comedy"],
    progressTags: ["any-progress"],
    themes: ["humor", "visceral"],
  },
  {
    id: 21,
    text: "who you're rooting for right now...",
    displayType: "lighthearted-fragment",
    tvmazeTypes: ["Reality", "Game Show"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["social", "character"],
  },
  {
    id: 22,
    text: "the moment you couldn't look away...",
    displayType: "lighthearted-fragment",
    tvmazeTypes: ["Reality", "Game Show"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["visceral"],
  },
  {
    id: 23,
    text: "your honest ranking of the cast...",
    displayType: "lighthearted-fragment",
    tvmazeTypes: ["Reality"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["social", "character"],
  },
  {
    id: 24,
    text: "who you'd want on your team...",
    displayType: "lighthearted-fragment",
    tvmazeTypes: ["Reality", "Game Show"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["social", "personal"],
  },
  {
    id: 25,
    text: "the choice that made no sense...",
    displayType: "lighthearted-fragment",
    tvmazeTypes: ["Reality", "Game Show"],
    genres: ["Comedy"],
    progressTags: ["any-progress"],
    themes: ["social", "character"],
  },
  {
    id: 26,
    text: "what you'd do differently...",
    displayType: "lighthearted-fragment",
    tvmazeTypes: ["Reality", "Game Show"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["personal", "social"],
  },
  {
    id: 27,
    text: "who you've changed your mind about...",
    displayType: "lighthearted-fragment",
    tvmazeTypes: ["Reality", "Game Show"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["character", "social"],
  },
  {
    id: 28,
    text: "the most chaotic moment so far...",
    displayType: "lighthearted-fragment",
    tvmazeTypes: ["Reality"],
    genres: ["Comedy"],
    progressTags: ["any-progress"],
    themes: ["visceral", "humor"],
  },
  {
    id: 29,
    text: "what you said out loud at the screen...",
    displayType: "lighthearted-fragment",
    tvmazeTypes: ["Reality", "Game Show"],
    genres: ["Comedy"],
    progressTags: ["any-progress"],
    themes: ["visceral", "humor"],
  },
  {
    id: 30,
    text: "who deserved better this episode...",
    displayType: "lighthearted-fragment",
    tvmazeTypes: ["Reality", "Game Show"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["character", "social"],
  },
  {
    id: 31,
    text: "the edit that told the whole story...",
    displayType: "lighthearted-fragment",
    tvmazeTypes: ["Reality"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["craft", "social"],
  },
  {
    id: 32,
    text: "your read on who wins this...",
    displayType: "lighthearted-fragment",
    tvmazeTypes: ["Reality", "Game Show"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["prediction", "social"],
  },
  {
    id: 33,
    text: "what you can't defend but love anyway...",
    displayType: "lighthearted-fragment",
    tvmazeTypes: ["Reality", "Game Show"],
    genres: ["Comedy"],
    progressTags: ["any-progress"],
    themes: ["personal", "humor"],
  },
  {
    id: 34,
    text: "the moment you picked your favorite...",
    displayType: "lighthearted-fragment",
    tvmazeTypes: ["Reality", "Game Show"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["character", "social"],
  },
  // ── Full Prompts ───────────────────────────────────────────────────────────
  {
    id: 35,
    text: "Was there a moment where you became aware of how intentional this was?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["craft", "contemplative"],
  },
  {
    id: 36,
    text: "What is this show actually about, underneath the plot?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["theme", "contemplative"],
  },
  {
    id: 37,
    text: "Did the structure of this episode do something unusual?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller", "Crime", "Mystery"],
    progressTags: ["any-progress"],
    themes: ["craft", "meta"],
  },
  {
    id: 38,
    text: "Was there a performance that made you forget you were watching?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Animation"],
    genres: ["Drama", "Comedy", "Thriller"],
    progressTags: ["any-progress"],
    themes: ["craft", "visceral"],
  },
  {
    id: 39,
    text: "What did the ending of this episode do that the beginning set up?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["craft", "contemplative"],
  },
  {
    id: 40,
    text: "Is there a scene that could only exist in this show — something no other show would do?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["craft", "comparison", "meta"],
  },
  {
    id: 41,
    text: "What's the show trusting you to figure out without explaining?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Documentary"],
    genres: ["Drama", "Thriller", "Mystery", "Crime"],
    progressTags: ["any-progress"],
    themes: ["craft", "contemplative"],
  },
  {
    id: 42,
    text: "Did anything feel off? Does it matter?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["craft", "contemplative"],
  },
  {
    id: 43,
    text: "What is the show withholding — and is the withholding doing something?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Documentary"],
    genres: ["Drama", "Thriller", "Mystery"],
    progressTags: ["any-progress"],
    themes: ["craft", "contemplative"],
  },
  {
    id: 44,
    text: "Is there a directorial or visual choice that keeps coming back in a way you've started to notice?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Documentary"],
    genres: ["Drama", "Thriller", "Horror"],
    progressTags: ["any-progress"],
    themes: ["craft", "meta", "contemplative"],
  },
  {
    id: 45,
    text: "What does the show's sense of humor — or lack of it — tell you about what it thinks it is?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["craft", "theme", "meta"],
  },
  {
    id: 46,
    text: "Is there a supporting character who's doing more narrative work than they're getting credit for?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Animation"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["craft", "character"],
  },
  {
    id: 47,
    text: "What's the difference between what the characters want and what the show seems to want for them?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Animation"],
    genres: ["Drama", "Comedy", "Thriller"],
    progressTags: ["any-progress"],
    themes: ["craft", "character", "theme"],
  },
  {
    id: 48,
    text: "What's the image you can't shake?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["visceral", "contemplative"],
  },
  {
    id: 49,
    text: "Was there a moment that made you physically react?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["visceral"],
  },
  {
    id: 50,
    text: "What made you pause, rewind, or sit up?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["visceral"],
  },
  {
    id: 51,
    text: "Did any scene make you want to look away — and did you?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Documentary"],
    genres: ["Drama", "Horror", "Thriller", "Crime"],
    progressTags: ["any-progress"],
    themes: ["visceral", "personal"],
  },
  {
    id: 52,
    text: "What moment hit differently than you expected?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["visceral"],
  },
  {
    id: 53,
    text: "Was there a line of dialogue that landed harder than it should have?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Animation"],
    genres: ["Drama", "Comedy", "Thriller"],
    progressTags: ["any-progress"],
    themes: ["visceral", "craft"],
  },
  {
    id: 54,
    text: "Was there a scene you wanted to be over — and stayed in anyway?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Documentary"],
    genres: ["Drama", "Horror", "Thriller"],
    progressTags: ["any-progress"],
    themes: ["visceral", "personal"],
  },
  {
    id: 55,
    text: "What moment made the world of the show feel completely real to you?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["visceral", "craft"],
  },
  {
    id: 56,
    text: "Was there a silence that did more than dialogue would have?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["any-progress"],
    themes: ["craft", "visceral"],
  },
  {
    id: 57,
    text: "What's a moment that made you feel something you don't have a clean word for?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Documentary"],
    genres: ["Drama", "Thriller", "Horror"],
    progressTags: ["any-progress"],
    themes: ["visceral", "contemplative"],
  },
  {
    id: 58,
    text: "Did the show use music in a way that changed how a scene landed?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["craft", "visceral"],
  },
  {
    id: 59,
    text: "Did anything in this remind you of your own life?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["personal"],
  },
  {
    id: 60,
    text: "Is there a character you recognized — in yourself or in someone you know?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["personal", "character"],
  },
  {
    id: 61,
    text: "What would you have done in that situation?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["personal", "character"],
  },
  {
    id: 62,
    text: "Has a show ever changed how you think about something the way this one might be?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Documentary"],
    genres: ["Drama", "Thriller", "Crime"],
    progressTags: ["any-progress"],
    themes: ["personal", "comparison", "theme"],
  },
  {
    id: 63,
    text: "What does this show understand about people that feels true?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["personal", "theme"],
  },
  {
    id: 64,
    text: "Is there something here you've been avoiding thinking about?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Documentary"],
    genres: ["Drama", "Thriller", "Crime"],
    progressTags: ["any-progress"],
    themes: ["personal", "contemplative"],
  },
  {
    id: 65,
    text: "Is there something this show understands about a relationship — friendship, family, love, rivalry — that feels unusually true?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["personal", "theme", "character"],
  },
  {
    id: 66,
    text: "Did watching this make you want to call someone?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Documentary"],
    genres: ["Drama", "Thriller", "Crime"],
    progressTags: ["any-progress"],
    themes: ["personal", "connection"],
  },
  {
    id: 67,
    text: "Is there a choice a character made that you've made — or almost made?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Animation"],
    genres: ["Drama", "Comedy", "Thriller", "Crime"],
    progressTags: ["any-progress"],
    themes: ["personal", "character"],
  },
  {
    id: 68,
    text: "What does this show illuminate about a part of life you don't usually examine?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Documentary"],
    genres: ["Drama", "Thriller", "Crime"],
    progressTags: ["any-progress"],
    themes: ["personal", "theme", "contemplative"],
  },
  {
    id: 69,
    text: "Has this show made you more or less patient with a particular kind of person?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Documentary"],
    genres: ["Drama", "Crime", "Thriller"],
    progressTags: ["any-progress"],
    themes: ["personal", "character", "theme"],
  },
  {
    id: 70,
    text: "What would you notice on a rewatch that you'd miss the first time?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["contemplative", "craft"],
  },
  {
    id: 71,
    text: "What is the show building toward that it hasn't said out loud yet?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller", "Mystery", "Crime"],
    progressTags: ["mid-season", "mid-series"],
    themes: ["contemplative", "prediction", "theme"],
  },
  {
    id: 72,
    text: "What question is this season asking that it hasn't answered?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["mid-season"],
    themes: ["contemplative", "theme"],
  },
  {
    id: 73,
    text: "What are you hoping for? What are you afraid of?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller", "Horror"],
    progressTags: ["mid-season", "pre-finale"],
    themes: ["contemplative", "personal", "prediction"],
  },
  {
    id: 74,
    text: "What's the thing the show keeps circling without landing on?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Documentary"],
    genres: ["Drama", "Thriller", "Mystery"],
    progressTags: ["mid-season", "mid-series"],
    themes: ["contemplative", "theme"],
  },
  {
    id: 75,
    text: "If you had to name the feeling this episode left you with, what would it be?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["contemplative", "visceral"],
  },
  {
    id: 76,
    text: "What's something small — a prop, a recurring image, a line reading — that might be doing more than it appears?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller", "Mystery"],
    progressTags: ["any-progress"],
    themes: ["craft", "contemplative", "meta"],
  },
  {
    id: 77,
    text: "What is the show refusing to explain — and do you respect that choice?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Documentary"],
    genres: ["Drama", "Thriller", "Mystery"],
    progressTags: ["any-progress"],
    themes: ["craft", "contemplative", "meta"],
  },
  {
    id: 78,
    text: "What's the most understated moment in what you've watched so far?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["any-progress"],
    themes: ["craft", "contemplative"],
  },
  {
    id: 79,
    text: "What would be lost if this show were made faster, or louder, or with more plot?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama"],
    progressTags: ["any-progress"],
    themes: ["craft", "contemplative", "meta"],
  },
  {
    id: 80,
    text: "What does this show reward in a viewer that most shows don't ask for?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Documentary"],
    genres: ["Drama", "Thriller"],
    progressTags: ["any-progress"],
    themes: ["craft", "contemplative", "meta"],
  },
  {
    id: 81,
    text: "Is there something you'd only want to talk about with someone who's seen this far?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["connection", "contemplative"],
  },
  {
    id: 82,
    text: "What's your read on where this is going — and do you want to be right?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["mid-season", "mid-series"],
    themes: ["connection", "prediction"],
  },
  {
    id: 83,
    text: "What question would you most want to ask someone else who just watched this?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["connection"],
  },
  {
    id: 84,
    text: "Is there something you thought that you almost don't want to admit?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["connection", "personal"],
  },
  {
    id: 85,
    text: "What would change your mind about how you're reading this?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["connection", "contemplative"],
  },
  {
    id: 86,
    text: "What's the take you're most uncertain about — the one you'd want to test on someone else?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["connection", "contemplative"],
  },
  {
    id: 87,
    text: "Is there something you loved that you suspect others found slow or difficult?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Documentary"],
    genres: ["Drama", "Thriller"],
    progressTags: ["any-progress"],
    themes: ["connection", "personal"],
  },
  {
    id: 88,
    text: "What would you want to know about how someone else experienced a specific moment?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["connection", "visceral"],
  },
  {
    id: 89,
    text: "What's the interpretation of a character or scene that would most change your own reading?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller", "Mystery"],
    progressTags: ["any-progress"],
    themes: ["connection", "character", "craft"],
  },
  {
    id: 90,
    text: "Is there something you noticed that you haven't seen anyone else mention?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["connection", "craft"],
  },
  {
    id: 91,
    text: "Who are you rooting for, and do you trust your own reasons?",
    displayType: "prompt",
    tvmazeTypes: ["Reality", "Game Show"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["social", "personal", "character"],
  },
  {
    id: 92,
    text: "Was there a moment that felt produced — and did it matter?",
    displayType: "prompt",
    tvmazeTypes: ["Reality"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["craft", "meta", "social"],
  },
  {
    id: 93,
    text: "What does this show reveal about people when the stakes are artificial?",
    displayType: "prompt",
    tvmazeTypes: ["Reality", "Game Show"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["theme", "social", "personal"],
  },
  {
    id: 94,
    text: "Who surprised you this episode, and how?",
    displayType: "prompt",
    tvmazeTypes: ["Reality", "Game Show"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["character", "social"],
  },
  {
    id: 95,
    text: "Did this change or complicate something you thought you understood?",
    displayType: "prompt",
    tvmazeTypes: ["Documentary"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["personal", "theme", "contemplative"],
  },
  {
    id: 96,
    text: "What do you want to know that the film didn't tell you?",
    displayType: "prompt",
    tvmazeTypes: ["Documentary"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["contemplative", "craft"],
  },
  {
    id: 97,
    text: "Was there a subject you found yourself judging — and then reconsidering?",
    displayType: "prompt",
    tvmazeTypes: ["Documentary"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["personal", "contemplative"],
  },
  {
    id: 98,
    text: "What stayed with you that the filmmakers might not have intended?",
    displayType: "prompt",
    tvmazeTypes: ["Documentary"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["visceral", "meta", "contemplative"],
  },
  {
    id: 99,
    text: "What was the funniest moment — and why did it work?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Animation"],
    genres: ["Comedy"],
    progressTags: ["any-progress"],
    themes: ["humor", "craft"],
  },
  {
    id: 100,
    text: "Did anything make you laugh and then feel something else underneath it?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Animation"],
    genres: ["Comedy"],
    progressTags: ["any-progress"],
    themes: ["humor", "visceral", "personal"],
  },
  {
    id: 101,
    text: "Is this show funnier or sadder than it appears on the surface?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Animation"],
    genres: ["Comedy"],
    progressTags: ["any-progress"],
    themes: ["theme", "humor", "contemplative"],
  },
  {
    id: 102,
    text: "What does this show understand about the thing it's making fun of?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Animation"],
    genres: ["Comedy"],
    progressTags: ["any-progress"],
    themes: ["theme", "craft", "humor"],
  },
  {
    id: 103,
    text: "Are you still surprised by this show, or is the formula the comfort?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Crime", "Mystery", "Legal", "Medical"],
    progressTags: ["mid-series"],
    themes: ["contemplative", "personal", "comparison"],
  },
  {
    id: 104,
    text: "Was there a case or storyline that stuck with you beyond the episode?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Crime", "Mystery", "Legal", "Medical"],
    progressTags: ["any-progress"],
    themes: ["visceral", "personal"],
  },
  {
    id: 105,
    text: "What keeps you coming back to this one specifically?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Crime", "Mystery", "Legal", "Medical"],
    progressTags: ["mid-series"],
    themes: ["personal", "contemplative"],
  },
  {
    id: 106,
    text: "What's the scene that would be hardest to explain to someone who hasn't seen the show?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["meta", "craft", "connection"],
  },
  {
    id: 107,
    text: "What has this show made you take more seriously than you expected to?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["personal", "theme"],
  },
  {
    id: 108,
    text: "What's one thing this show gets wrong — about people, about the world, about its own genre?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["meta", "craft", "contemplative"],
  },
  {
    id: 109,
    text: "Is there a moment where you felt the show was made specifically for you?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["personal", "visceral"],
  },
  {
    id: 110,
    text: "What do you think the people who made this are most proud of?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["meta", "craft", "contemplative"],
  },
  {
    id: 111,
    text: "Defend a choice the show made that you didn't like at first.",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["craft", "contemplative", "connection"],
  },
  {
    id: 112,
    text: "Write about the character getting the least attention right now.",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Animation"],
    genres: ["Drama", "Comedy", "Thriller"],
    progressTags: ["any-progress"],
    themes: ["character", "craft"],
  },
  {
    id: 113,
    text: "What's the show not saying that it might be thinking?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Documentary"],
    genres: ["Drama", "Thriller", "Crime"],
    progressTags: ["any-progress"],
    themes: ["theme", "contemplative", "meta"],
  },
  {
    id: 114,
    text: "If this show had a thesis, what would it be?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["theme", "contemplative"],
  },
  {
    id: 115,
    text: "What would a skeptic of this show get wrong about it?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["connection", "meta", "contemplative"],
  },
  {
    id: 116,
    text: "What does this show get right that most shows get wrong?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["craft", "comparison", "meta"],
  },
  {
    id: 117,
    text: "Pick one scene and describe only what you saw, not what it meant.",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["visceral", "contemplative", "craft"],
  },
  {
    id: 118,
    text: "What are you hoping doesn't happen next?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller", "Horror", "Mystery"],
    progressTags: ["mid-season", "pre-finale"],
    themes: ["prediction", "personal"],
  },
  {
    id: 119,
    text: "What were you expecting before you pressed play — and were you right?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["first-episode"],
    themes: ["personal", "comparison"],
  },
  {
    id: 120,
    text: "What made you decide to keep watching?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["first-episode", "early"],
    themes: ["personal", "contemplative"],
  },
  {
    id: 121,
    text: "Did this feel like a show that knows what it is, or one still figuring itself out?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["first-episode", "early"],
    themes: ["craft", "meta"],
  },
  {
    id: 122,
    text: "Who caught your attention first, and why?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["first-episode"],
    themes: ["character", "personal"],
  },
  {
    id: 123,
    text: "What's the one thing this pilot did that hooked you?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["first-episode"],
    themes: ["craft", "personal"],
  },
  {
    id: 124,
    text: "What questions do you have that you hope the show answers — and which ones do you hope it doesn't?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller", "Mystery"],
    progressTags: ["first-episode"],
    themes: ["contemplative", "prediction"],
  },
  {
    id: 125,
    text: "What's your first instinct about this show? Hold onto it. It'll be interesting to revisit.",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["first-episode"],
    themes: ["personal", "contemplative", "comparison"],
  },
  {
    id: 126,
    text: "Was there a character you immediately trusted — or immediately didn't?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["first-episode"],
    themes: ["character", "personal"],
  },
  {
    id: 127,
    text: "What's the world of this show? Did it feel lived-in or constructed?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["first-episode"],
    themes: ["craft", "meta"],
  },
  {
    id: 128,
    text: "Did the tone match what you thought you were signing up for?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["first-episode"],
    themes: ["personal", "meta"],
  },
  {
    id: 129,
    text: "What's the first thing this show did that felt genuinely its own?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["first-episode"],
    themes: ["craft", "meta"],
  },
  {
    id: 130,
    text: "Is this a show that explains itself, or one that drops you in and expects you to catch up?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["first-episode"],
    themes: ["craft", "meta", "personal"],
  },
  {
    id: 131,
    text: "Is the show becoming something different than the pilot suggested?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["early"],
    themes: ["craft", "meta", "comparison"],
  },
  {
    id: 132,
    text: "Which character are you most interested in right now — and is it who you expected?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["early"],
    themes: ["character", "personal"],
  },
  {
    id: 133,
    text: "What has surprised you about the direction this is going?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["early"],
    themes: ["craft", "personal"],
  },
  {
    id: 134,
    text: "Is there something the show is setting up that you're not sure you trust yet?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller", "Mystery"],
    progressTags: ["early"],
    themes: ["craft", "contemplative"],
  },
  {
    id: 135,
    text: "What do you think this show is really about — your best guess so far?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["early"],
    themes: ["theme", "contemplative"],
  },
  {
    id: 136,
    text: "What relationship are you most invested in right now?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Animation"],
    genres: ["Drama", "Comedy", "Romance"],
    progressTags: ["early", "mid-season"],
    themes: ["character", "personal"],
  },
  {
    id: 137,
    text: "Is the show moving at the right pace, or are you ahead of it — or behind?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["early", "mid-season"],
    themes: ["craft", "personal"],
  },
  {
    id: 138,
    text: "What do you think the show is afraid to do that you wish it would?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller", "Comedy"],
    progressTags: ["early", "mid-season"],
    themes: ["craft", "contemplative"],
  },
  {
    id: 139,
    text: "Has anything made you reconsider your first impression?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["early", "mid-season"],
    themes: ["personal", "comparison"],
  },
  {
    id: 140,
    text: "What detail keeps coming back that you think might matter later?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller", "Mystery", "Crime"],
    progressTags: ["early", "mid-season"],
    themes: ["craft", "contemplative", "prediction"],
  },
  {
    id: 141,
    text: "How has your read on the main character shifted from episode one?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["early", "mid-season"],
    themes: ["character", "comparison"],
  },
  {
    id: 142,
    text: "What has this season built that you didn't see coming?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["mid-season", "season-ending"],
    themes: ["craft", "personal"],
  },
  {
    id: 143,
    text: "Is this show earning your investment? What's making you stay?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["early", "mid-season"],
    themes: ["personal", "contemplative"],
  },
  {
    id: 144,
    text: "What's the thing this show does better than anything else you're watching?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["early", "mid-season"],
    themes: ["comparison", "craft"],
  },
  {
    id: 145,
    text: "What would you tell someone who just started to make them stick with it?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["mid-season"],
    themes: ["connection", "personal"],
  },
  {
    id: 146,
    text: "What has this season done that you didn't expect it to be capable of?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["mid-season", "season-ending"],
    themes: ["craft", "personal"],
  },
  {
    id: 147,
    text: "Is there a character you started out dismissing who's become interesting?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["mid-season"],
    themes: ["character", "personal"],
  },
  {
    id: 148,
    text: "What's the emotional core of this season — what is it really about underneath everything?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller", "Crime"],
    progressTags: ["mid-season", "season-ending"],
    themes: ["theme", "contemplative"],
  },
  {
    id: 149,
    text: "Has the show made you care about something you didn't think you cared about?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["mid-season"],
    themes: ["personal", "theme"],
  },
  {
    id: 150,
    text: "What's the tension this season is living inside — and is it sustaining it?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["mid-season"],
    themes: ["craft", "theme"],
  },
  {
    id: 151,
    text: "Did the finale pay off what the season was building — or did it go somewhere else?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["season-ending"],
    themes: ["craft", "endings"],
  },
  {
    id: 152,
    text: "What did you need to happen that didn't? What happened that you didn't need?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["season-ending"],
    themes: ["personal", "endings"],
  },
  {
    id: 153,
    text: "What's the image or moment you'll carry from this season?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["season-ending"],
    themes: ["visceral", "endings"],
  },
  {
    id: 154,
    text: "Did the ending change how you see what came before?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller", "Mystery"],
    progressTags: ["season-ending"],
    themes: ["contemplative", "endings", "craft"],
  },
  {
    id: 155,
    text: "What does the show still owe you going into the next season?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["season-ending"],
    themes: ["personal", "prediction", "endings"],
  },
  {
    id: 156,
    text: "Is this a show that sticks its landings, or one you love despite them?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["season-ending", "post-show"],
    themes: ["craft", "personal", "comparison"],
  },
  {
    id: 157,
    text: "What did the finale reframe about everything that came before it?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller", "Mystery"],
    progressTags: ["season-ending"],
    themes: ["craft", "contemplative", "endings"],
  },
  {
    id: 158,
    text: "Did any character end the season somewhere you didn't see coming?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["season-ending"],
    themes: ["character", "endings"],
  },
  {
    id: 159,
    text: "What thread is the show leaving unresolved going into next season — intentionally or not?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["season-ending"],
    themes: ["craft", "prediction", "endings"],
  },
  {
    id: 160,
    text: "Did the finale feel like a destination the season was heading toward, or a decision made at the last minute?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["season-ending"],
    themes: ["craft", "endings"],
  },
  {
    id: 161,
    text: "What's the last image or line that's still with you?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["season-ending", "post-show"],
    themes: ["visceral", "endings"],
  },
  {
    id: 162,
    text: "Did the show pick up where you left it emotionally — or did it feel different coming back?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["new-season"],
    themes: ["personal", "comparison"],
  },
  {
    id: 163,
    text: "Is this a new chapter, or more of the same? And which did you want?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["new-season"],
    themes: ["personal", "comparison", "craft"],
  },
  {
    id: 164,
    text: "Has anything in your own life changed the way you're watching this season?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["new-season"],
    themes: ["personal"],
  },
  {
    id: 165,
    text: "What are you hoping this season does differently — and what do you hope it protects?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["new-season"],
    themes: ["personal", "prediction"],
  },
  {
    id: 166,
    text: "Does the show feel like it missed you while you were gone — or like it moved on without you?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["new-season"],
    themes: ["personal", "contemplative"],
  },
  {
    id: 167,
    text: "What relationship are you most curious about picking back up?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Animation"],
    genres: ["Drama", "Comedy", "Romance"],
    progressTags: ["new-season"],
    themes: ["character", "personal"],
  },
  {
    id: 168,
    text: "Did the premiere earn the gap — did it feel like something worth waiting for?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["new-season"],
    themes: ["craft", "personal"],
  },
  {
    id: 169,
    text: "What do you want this season to be brave enough to do?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["new-season"],
    themes: ["personal", "prediction", "craft"],
  },
  {
    id: 170,
    text: "Is there something from last season that still feels unresolved in a way that bothers you?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller", "Mystery"],
    progressTags: ["new-season"],
    themes: ["personal", "endings", "prediction"],
  },
  {
    id: 171,
    text: "What did you remember wrong?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["new-season"],
    themes: ["personal", "contemplative"],
  },
  {
    id: 172,
    text: "Is this show still surprising you, or have you learned how it works?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["mid-series"],
    themes: ["craft", "personal", "comparison"],
  },
  {
    id: 173,
    text: "What's the thing keeping you invested that wasn't there in season one?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["mid-series"],
    themes: ["personal", "comparison"],
  },
  {
    id: 174,
    text: "Has any character grown in a direction you didn't want — and do you respect it anyway?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Comedy", "Thriller"],
    progressTags: ["mid-series"],
    themes: ["character", "personal"],
  },
  {
    id: 175,
    text: "What has this show given up to become what it is now?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["mid-series"],
    themes: ["craft", "comparison", "contemplative"],
  },
  {
    id: 176,
    text: "Is there a storyline you wish the show would let go of? One you wish it would return to?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["mid-series"],
    themes: ["personal", "craft"],
  },
  {
    id: 177,
    text: "Where do you think this is all going — and do you want to find out?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller", "Mystery"],
    progressTags: ["mid-series"],
    themes: ["prediction", "personal"],
  },
  {
    id: 178,
    text: "What has the show sacrificed to get here — and was it worth it?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["mid-series"],
    themes: ["craft", "comparison", "contemplative"],
  },
  {
    id: 179,
    text: "Is there a character who's become the heart of the show without it being announced?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Comedy", "Thriller"],
    progressTags: ["mid-series"],
    themes: ["character", "craft"],
  },
  {
    id: 180,
    text: "What's the best thing this show has done in the last few episodes that went underappreciated?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["mid-series"],
    themes: ["craft", "connection"],
  },
  {
    id: 181,
    text: "Has the show changed your mind about anything — a character, a choice, a theme?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["mid-series"],
    themes: ["personal", "character", "theme"],
  },
  {
    id: 182,
    text: "What would you cut if you could — and what would you never touch?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["mid-series"],
    themes: ["craft", "personal"],
  },
  {
    id: 183,
    text: "Which season do you return to in your head the most — and why?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["comparing-seasons"],
    themes: ["comparison", "personal", "contemplative"],
  },
  {
    id: 184,
    text: "Has your favorite character changed across seasons, or stayed the same in ways that feel true?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Comedy", "Thriller"],
    progressTags: ["comparing-seasons"],
    themes: ["character", "comparison"],
  },
  {
    id: 185,
    text: "Is this a show that's getting better, or one you love most for what it was?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["comparing-seasons"],
    themes: ["comparison", "personal"],
  },
  {
    id: 186,
    text: "What did an earlier season understand about this story that a later one lost — or found?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["comparing-seasons"],
    themes: ["craft", "comparison", "contemplative"],
  },
  {
    id: 187,
    text: "If you had to recommend a season to someone who'd never seen the show, which one and why?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["comparing-seasons"],
    themes: ["comparison", "connection"],
  },
  {
    id: 188,
    text: "What did this show figure out somewhere in the middle that it didn't know at the start?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["comparing-seasons"],
    themes: ["craft", "comparison"],
  },
  {
    id: 189,
    text: "Is there a season that felt like a wrong turn — and did the show recover?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["comparing-seasons"],
    themes: ["craft", "comparison", "endings"],
  },
  {
    id: 190,
    text: "What has stayed completely consistent across every season, for better or worse?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["comparing-seasons"],
    themes: ["comparison", "theme", "craft"],
  },
  {
    id: 191,
    text: "If you could give one season to a writer's room struggling with a different show, which one and why?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["comparing-seasons"],
    themes: ["craft", "comparison", "meta"],
  },
  {
    id: 192,
    text: "What does the arc of this show say about the people who made it?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Documentary"],
    genres: ["Drama", "Thriller"],
    progressTags: ["comparing-seasons"],
    themes: ["meta", "theme", "contemplative"],
  },
  {
    id: 193,
    text: "What does this show owe you before it ends?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["pre-finale"],
    themes: ["personal", "endings", "prediction"],
  },
  {
    id: 194,
    text: "What outcome are you hoping for — and what outcome would feel true, even if it hurts?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["pre-finale"],
    themes: ["personal", "endings", "prediction"],
  },
  {
    id: 195,
    text: "Is there a character whose ending matters most to you?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["pre-finale"],
    themes: ["character", "personal", "endings"],
  },
  {
    id: 196,
    text: "What would a perfect finale look like? What would a perfect finale feel like?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["pre-finale"],
    themes: ["personal", "endings", "contemplative"],
  },
  {
    id: 197,
    text: "What are you most afraid of losing?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["pre-finale"],
    themes: ["personal", "endings"],
  },
  {
    id: 198,
    text: "What question has this show been asking for seasons that it now has to answer?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller", "Mystery"],
    progressTags: ["pre-finale"],
    themes: ["theme", "endings", "contemplative"],
  },
  {
    id: 199,
    text: "What character arc needs to resolve for the show to feel complete?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["pre-finale"],
    themes: ["character", "endings"],
  },
  {
    id: 200,
    text: "Is there a relationship the show has built for years that you're terrified it's going to mishandle?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller", "Romance"],
    progressTags: ["pre-finale"],
    themes: ["character", "personal", "endings"],
  },
  {
    id: 201,
    text: "What would feel like a betrayal — not a disappointing ending, but a wrong one?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["pre-finale"],
    themes: ["personal", "endings", "theme"],
  },
  {
    id: 202,
    text: "What has this show been saying all along that the finale needs to honor?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["pre-finale"],
    themes: ["theme", "endings", "contemplative"],
  },
  {
    id: 203,
    text: "Are you watching more carefully now, knowing it's almost over?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["pre-finale"],
    themes: ["personal", "contemplative"],
  },
  {
    id: 204,
    text: "Did it earn its ending?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["post-show"],
    themes: ["endings", "craft", "contemplative"],
  },
  {
    id: 205,
    text: "What stayed with you that you didn't expect?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["post-show"],
    themes: ["visceral", "personal"],
  },
  {
    id: 206,
    text: "Is there a scene from the finale you keep thinking about?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["post-show"],
    themes: ["visceral", "endings"],
  },
  {
    id: 207,
    text: "What do you wish had been different — and does it change how you feel about the whole?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["post-show"],
    themes: ["personal", "endings", "comparison"],
  },
  {
    id: 208,
    text: "What does this show mean to you now that it's over?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["post-show"],
    themes: ["personal", "contemplative", "endings"],
  },
  {
    id: 209,
    text: "Is this a show you'll rewatch, or one you want to preserve exactly as you first experienced it?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["post-show"],
    themes: ["personal", "contemplative"],
  },
  {
    id: 210,
    text: "What did this show give you that you couldn't have gotten anywhere else?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["post-show"],
    themes: ["personal", "contemplative"],
  },
  {
    id: 211,
    text: "What's the first thing you'd say to someone who just finished it?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["post-show"],
    themes: ["connection", "endings"],
  },
  {
    id: 212,
    text: "Which character will you carry with you the longest?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["post-show"],
    themes: ["character", "personal", "endings"],
  },
  {
    id: 213,
    text: "Did the show end at the right moment, or did it go on too long — or not long enough?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["post-show"],
    themes: ["craft", "endings", "personal"],
  },
  {
    id: 214,
    text: "Is there a choice the finale made that you're still arguing with?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Drama", "Thriller"],
    progressTags: ["post-show"],
    themes: ["endings", "personal", "craft"],
  },
  {
    id: 215,
    text: "What did this show teach you about the kind of stories you need?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["post-show"],
    themes: ["personal", "contemplative", "theme"],
  },
  {
    id: 216,
    text: "If you could give this show one more episode, what would it be?",
    displayType: "prompt",
    tvmazeTypes: ["all"],
    genres: ["all-genre"],
    progressTags: ["post-show"],
    themes: ["personal", "endings", "craft"],
  },
  {
    id: 217,
    text: "What does this cast reveal about the culture it was assembled from?",
    displayType: "prompt",
    tvmazeTypes: ["Reality"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["social", "theme", "meta"],
  },
  {
    id: 218,
    text: "Is there a moment where the format of the show became more interesting than the content?",
    displayType: "prompt",
    tvmazeTypes: ["Reality", "Game Show"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["meta", "craft"],
  },
  {
    id: 219,
    text: "What's the thing this show is secretly about underneath the competition?",
    displayType: "prompt",
    tvmazeTypes: ["Reality", "Game Show"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["theme", "contemplative"],
  },
  {
    id: 220,
    text: "Which relationship in the cast is the most interesting — not the most dramatic, the most interesting?",
    displayType: "prompt",
    tvmazeTypes: ["Reality"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["social", "character"],
  },
  {
    id: 221,
    text: "Did any contestant make a choice that was wrong strategically but right as a person?",
    displayType: "prompt",
    tvmazeTypes: ["Reality", "Game Show"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["character", "personal", "social"],
  },
  {
    id: 222,
    text: "Whose perspective is missing from this film — who isn't being heard?",
    displayType: "prompt",
    tvmazeTypes: ["Documentary"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["meta", "theme", "craft"],
  },
  {
    id: 223,
    text: "Did the filmmakers' presence change what you were watching in a way you felt?",
    displayType: "prompt",
    tvmazeTypes: ["Documentary"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["meta", "craft"],
  },
  {
    id: 224,
    text: "What do you think the subjects of this film thought they were signing up for?",
    displayType: "prompt",
    tvmazeTypes: ["Documentary"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["meta", "personal", "social"],
  },
  {
    id: 225,
    text: "Is there a moment where the film seems to be arguing something without saying it directly?",
    displayType: "prompt",
    tvmazeTypes: ["Documentary"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["craft", "theme", "contemplative"],
  },
  {
    id: 226,
    text: "What does this documentary assume about its audience — and is it right about you?",
    displayType: "prompt",
    tvmazeTypes: ["Documentary"],
    genres: ["all-genre"],
    progressTags: ["any-progress"],
    themes: ["meta", "personal"],
  },
  {
    id: 227,
    text: "What is this show sad about — even if it never says so directly?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Animation"],
    genres: ["Comedy"],
    progressTags: ["any-progress"],
    themes: ["theme", "contemplative"],
  },
  {
    id: 228,
    text: "Is there a recurring bit or running joke that's gotten richer over time?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Animation"],
    genres: ["Comedy"],
    progressTags: ["mid-season", "mid-series"],
    themes: ["humor", "craft"],
  },
  {
    id: 229,
    text: "What does this comedy understand about failure, embarrassment, or awkwardness that feels specifically true?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Animation"],
    genres: ["Comedy"],
    progressTags: ["any-progress"],
    themes: ["theme", "personal", "humor"],
  },
  {
    id: 230,
    text: "Is there a character whose comedic role is covering for something more complicated underneath?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Animation"],
    genres: ["Comedy"],
    progressTags: ["any-progress"],
    themes: ["character", "theme", "craft"],
  },
  {
    id: 231,
    text: "What's the line between this show being affectionate about its characters and being cruel — and does it stay on the right side?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted", "Animation"],
    genres: ["Comedy"],
    progressTags: ["any-progress"],
    themes: ["theme", "craft", "personal"],
  },
  {
    id: 232,
    text: "What does the case or storyline this episode say about the world the show is set in?",
    displayType: "prompt",
    tvmazeTypes: ["Scripted"],
    genres: ["Crime", "Mystery", "Legal", "Medical"],
    progressTags: ["any-progress"],
    themes: ["theme", "craft"],
  },
];
